# copied straight from the docs: circleci.com/developer/orbs/orb/circleci/gradle
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          test_results_path: app/build/test-results/test

